
language: C++

sudo: enabled
dist: trusty

notifications:
  email: false

compiler: 
  - clang

#env:
#  global:
#    - MPI=mpich
#    - F77=gfortran-5
#    - PATH=/usr/lib/ccache/:$PATH
#  matrix:
#    - CC=gcc-5 CXX=g++-5
#    - CC=clang-3.8 CXX=clang++-3.8

#cache:
#  directories:
#    - $HOME/.ccache


# If before_install, install or before_script return a non-zero exit code, the build is errored and stops immediately

#before_install: true

install: 
  - ./autogen.sh

before_script: 
  - ls

# If script returns a non-zero exit code, the build is failed, but continues to run before being marked as failed.

script: 
  - ./configure 
  - make

# (Optional) for cleaning up cache
#before_cache: true

# The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as a failure.

#after_success: true

#after_failure: true

#before_deploy: true

#deploy: true

#after_deploy: true

#after_script: true
